In [2]:
import os
import warnings
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import datetime as dt
import math

from pandas.plotting import autocorrelation_plot
from statsmodels.tsa.statespace.sarimax import SARIMAX
from sklearn.preprocessing import MinMaxScaler
#from common.utils import load_data, mape
from IPython.display import Image

%matplotlib inline
pd.options.display.float_format = '{:,.2f}'.format
np.set_printoptions(precision=2)
warnings.filterwarnings("ignore") # specify to ignore warning messages

In [18]:
#mypath =  r'G:\My Drive\Dropbox\IIM-Aditya\Teaching\Executive courses\MSDSM -Business Analytics\codes\TSA&F\\'

#flipkart = pd.read_csv(mypath+ r'flipkart.csv')
#a = pd.read_csv(mypath+ r'flipkart-i.csv')

#flipkart.head()
#a.head()

Oct-13    1    2     3     4     5     6    7    8    9  ...  64   65   66  \
0  Counts  315  425  1013  1265  1381  1624  107  162  396  ...  68  132  253   

   67  68  69  70   71   72     73  
0   9  16  42  56  122  258  11299  

[1 rows x 74 columns]

In [54]:
mat=[[0.2,0,0.8],[0.5,0,.5],[0.3,0.7,0]]

In [55]:
print(mat)

[[0.2, 0, 0.8], [0.5, 0, 0.5], [0.3, 0.7, 0]]


In [56]:

np.dot(mat, mat)

array([[0.28, 0.56, 0.16],
       [0.25, 0.35, 0.4 ],
       [0.41, 0.  , 0.59]])

In [57]:
np.set_printoptions(precision=5)

from numpy.linalg import matrix_power
print(np.linalg.matrix_power(mat,5))

[[0.34216 0.25424 0.4036 ]
 [0.32035 0.2912  0.38845]
 [0.31025 0.28959 0.40016]]


In [43]:
biscuit=[[0.8189,0.0882,0.0472,0.0457],
         [0.1128,0.7180,0.0902,0.0789],
         [0.2077,.086,0.602,0.1],
         [0.0663,0.0964,0.0964,0.7410]]
  
a=[450,225,175,150]
print(biscuit)

[[0.8189, 0.0882, 0.0472, 0.0457], [0.1128, 0.718, 0.0902, 0.0789], [0.2077, 0.086, 0.602, 0.1], [0.0663, 0.0964, 0.0964, 0.741]]


In [44]:
x=np.matrix(biscuit)
x.sum(axis=1)

matrix([[1.],
        [1.],
        [1.],
        [1.]])

In [49]:
np.dot(a,np.linalg.matrix_power(biscuit,50))

array([388.52, 234.42, 147.24, 197.31])

In [13]:
biscuitn=[[0.8189,0.0882,0.0472,0.0457],
         [0.1128,0.7180,0.0903,0.0789],
         [0.2077,.0849,0.6011,0.1063],
         [0.0680,0.0964,0.0946,0.7410]]
  

In [14]:
xn=np.matrix(biscuitn)
xn.sum(axis=1)

matrix([[1.],
        [1.],
        [1.],
        [1.]])

In [50]:
an=[0.2,0.8]
brand=np.matrix([[0.8,0.2],[0.25,0.75]])


In [53]:
i=0
while (i<30):
    print(np.dot(an,np.linalg.matrix_power(brand,i)))
    i=i+1

[[0.2 0.8]]
[[0.36 0.64]]
[[0.45 0.55]]
[[0.5 0.5]]
[[0.52 0.48]]
[[0.54 0.46]]
[[0.55 0.45]]
[[0.55 0.45]]
[[0.55 0.45]]
[[0.55 0.45]]
[[0.55 0.45]]
[[0.56 0.44]]
[[0.56 0.44]]
[[0.56 0.44]]
[[0.56 0.44]]
[[0.56 0.44]]
[[0.56 0.44]]
[[0.56 0.44]]
[[0.56 0.44]]
[[0.56 0.44]]
[[0.56 0.44]]
[[0.56 0.44]]
[[0.56 0.44]]
[[0.56 0.44]]
[[0.56 0.44]]
[[0.56 0.44]]
[[0.56 0.44]]
[[0.56 0.44]]
[[0.56 0.44]]
[[0.56 0.44]]


In [17]:


def steady_state_prop(
  p=np.matrix([
          [0,.2,.4,.4],
          [.2,0,.4,.4],
          [.2,.3,0,.5],
          [.3,.4,.3,0]
          ])):
    dim = p.shape[0]
    q = (p-np.eye(dim))
    ones = np.ones(dim)
    q = np.c_[q,ones]
    QTQ = np.dot(q, q.T)
    bQT = np.ones(dim)
    return np.linalg.solve(QTQ,bQT)

In [18]:
flight=np.matrix([[0.45,.3,.2,.05],[0.15,0.6,0.15,0.1],[0.1,0.3,0.4,0.2],[0,.1,.7,.2]])

In [19]:
steady_state_prop(np.matrix(flight))

array([0.16279, 0.38953, 0.31105, 0.13663])

In [20]:
steady_state_prop(np.matrix(biscuit))

array([0.40291, 0.24275, 0.15258, 0.20176])

In [3]:
airwaves=np.matrix([[1,0,0,0,0,0],
                    [0,1,0,0,0,0],
                    [0.05,0.05,0.9,0,0,0],
                    [0.1,0.05,0,0.8,0.05,0],
                    [0.2,0.1,0,0.05,0.6,0.05],
                    [0.1,0.2,0,0,0,0.7],])

In [4]:
airwavesQ=airwaves[2:,2:]
I=np.identity(4)


In [5]:
F=I-airwavesQ

In [6]:
from numpy.linalg import inv
FI=inv(F)

In [7]:
airwavesR=airwaves[2:,:2]
np.dot(FI,airwavesR)


matrix([[0.5 , 0.5 ],
        [0.66, 0.34],
        [0.62, 0.38],
        [0.33, 0.67]])

In [20]:
np.dot(FI,np.ones((4,1)))

matrix([[10.  ],
        [ 5.91],
        [ 3.66],
        [ 3.33]])